name: Automatic Rebase
maintainer: EIG
inputs:
  squash_commit:
    description: optional squash commit message when rebased
    required: false
  rebase:
    description: Should rebase head onto base branch
    required: false
    default: true
  merge:
    description: Should merge head into base branch
    required: false
    default: true
  pr_number:
    required: true
    description: PR number
runs:
  using: 'docker'
  image: 'Dockerfile'
